[project]
name = "biobeamer"
version = "0.1.0"
description = "Collecting instrument data using BioBeamer"
authors = [
    { name = "Christian Panse", email = "panse@fgcz.ch" }
    { name = "Witold Wolski", email = "wew@fgcz.uzh.ch" }
    { name  = "Claudio Cannizzaro", email= "claudio.cannizzaro@fgcz.uzh.ch"}    
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "lxml",
    "platformdirs>=4.0.0",
    "paramiko",
]

[project.optional-dependencies]
development = [
    "pytest>=7.4.4",
    "pytest-mock",
    "coverage>=7.2.7",
]

[project.scripts]
biobeamer = "biobeamer.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
biobeamer = ["configs/*"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
