[project]
name = "biobeamer"
version = "0.1.0"
description = "Collecting instrument data using BioBeamer"
authors = [
    { name = "Christian Panse", email = "panse@fgcz.ch" }
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "lxml",
]

[project.optional-dependencies]
development = [
    "pytest>=7.4.4",
    "coverage>=7.2.7",
]

[project.scripts]
biobeamer2 = "biobeamer2:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
